# Generated by Django 3.2.5 on 2022-07-14 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='date_of_activation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
