# Generated by Django 3.2.5 on 2022-07-14 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_facility', '0002_customers_date_of_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_wash_programs',
            name='date_of_launch',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
