# Generated by Django 3.2.5 on 2022-07-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_facility', '0003_car_wash_programs_date_of_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers_car_wash_programs',
            name='with_discount',
            field=models.BooleanField(default=False),
        ),
    ]
