# Generated by Django 3.2.5 on 2022-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_facility', '0006_auto_20220717_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_car_wash_programs',
            name='date_of_car_wash',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customers_car_wash_programs',
            name='end_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_car_wash_programs',
            name='end_minutes',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers_car_wash_programs',
            name='start_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers_car_wash_programs',
            name='start_minutes',
            field=models.IntegerField(),
        ),
    ]
